package ast;

/**
 * Interface for AST nodes that can be statements
 * 
 * These are the nodes that are generated by <code>base_statement</code> constructs
 */

public interface StatementNode extends ASTNode {
	
}
